language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
# first update setuptools and pip
before_install:
  - pip install -U setuptools pip
# command to install dependencies
install:
  - pip install -U --upgrade-strategy=eager -r dev-requirements.txt
# command to run tests
script:
  - pytest --cache-clear
